project:
  type: website

website:
  title: "RtoProd.com"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/RtoProd/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: minty
    css: styles.css

editor: visual

